### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by humorless** [humorless/trading#1]
# Plumbing Tasks
- [x] prepare a `jobs` table
- [x] write SQL query to read `jobs` as a queue 
- [x] http request library, json library, config library
- [x] mark the job as "done" (when http request is successful)
- [x] processing order of the jobs of the same key: order by `updated` and `priority`
- [x] prepare a `keys` table
- [x] add the required constraints for `keys` and `jobs`
- [x] initialize the threads: loading the keys and creating the threads
- [x] long running child thread pass the key to `process-job` function
- [x] integrate with a proper log library 
- [x] prepare certain thread manipulation code

# Todo
- [ ] early return when the query results is empty  
- [ ] add the http request and combine the http request with `process-job` function
- [ ] main thread recreates the child thread when it terminates -> Probably need to use atom to manage the thread-list 
- [ ] trading script support
- [ ] deployment  -> ref [uberjar](https://blog.michielborkent.nl/new-clojure-project-quickstart.html)

# Nice to have
- [ ] Consider the [uncaught exceptions inside the thread ](https://stuartsierra.com/2015/05/27/clojure-uncaught-exceptions)

# Testing criteria
- [ ] verify if the http request has timeout. (connection timeout, response timeout)
- [ ] verify if when the http request fails the record will be the same. (record will be updated only when http request is successful.)
- [ ] verify if a thread stops because of exception, it will be recreated.
